#!/usr/bin/env python3
"""Emit the generated Rust parameter and test-vector modules.

RESEARCH USE ONLY. See `crates/akita-transcript/src/poseidon2/mod.rs`.

Usage (from the repository root):

  sage crates/akita-transcript/tools/poseidon2_params_p64m59.sage 3 > a3.json
  sage crates/akita-transcript/tools/poseidon2_params_p64m59.sage 7 > a7.json
  python3 crates/akita-transcript/tools/poseidon2_sponge_reference.py \
      a3.json a7.json > vectors.json
  python3 crates/akita-transcript/tools/emit_rust_params.py \
      a3.json a7.json vectors.json crates/akita-transcript/src/poseidon2
"""

import datetime
import hashlib
import json
import os
import sys

TAGS = {3: "akita-pcs/transcript/v1/p2a3", 7: "akita-pcs/transcript/v1/p2a7"}

BANNER = """\
// GENERATED FILE - DO NOT EDIT BY HAND.
//
// UNAUDITED RESEARCH CRYPTOGRAPHY - NOT FOR PRODUCTION.
// This is a new Poseidon2 instance over p* = 2^64 - 59, a prime at which no
// arithmetization-oriented permutation has received third-party cryptanalysis
// at full parameters. Do not deploy.
//
// Generated by:
//   sage crates/akita-transcript/tools/poseidon2_params_p64m59.sage {alpha} \\
//       > alpha{alpha}.json
//   python3 crates/akita-transcript/tools/poseidon2_sponge_reference.py \\
//       alpha3.json alpha7.json > vectors.json
//   python3 crates/akita-transcript/tools/emit_rust_params.py \\
//       alpha3.json alpha7.json vectors.json crates/akita-transcript/src/poseidon2
//
// Generator: crates/akita-transcript/tools/poseidon2_params_p64m59.sage
//   sha256 {script_sha}
// Upstream:  crates/akita-transcript/tools/upstream_poseidon2_rust_params.sage.txt
//   (HorizenLabs/poseidon2 poseidon2_rust_params.sage,
//    sha256 c301c6d074b58cc27f117f59971f405a16c57d10e6140f1025643fa25ba75223)
// Generated on {date} with {sage_version}.
"""


def fmt_u64_array(name, values, doc):
    lines = [doc, "#[rustfmt::skip]", f"const {name}: [u64; {len(values)}] = ["]
    for i in range(0, len(values), 4):
        chunk = ", ".join(f"{v}" for v in values[i:i + 4])
        lines.append(f"    {chunk},")
    lines.append("];")
    return "\n".join(lines)


def emit_params(params, script_sha, sage_version):
    alpha = params["alpha"]
    checks = params["checks"]
    tag = TAGS[alpha]
    assert len(tag) == 28, tag

    head = BANNER.format(
        alpha=alpha,
        script_sha=script_sha,
        date=datetime.date.today().isoformat(),
        sage_version=sage_version,
    )

    verification = [
        "//",
        "// Verification performed by the generator (all must be true):",
        f"//   gcd(alpha, p-1)                      = {checks['gcd_alpha_p_minus_1']}",
        f"//   M4 MDS (exhaustive, all 69 minors)   = {checks['m4_mds_exhaustive']}",
        f"//   external matrix invertible           = {checks['external_invertible']}",
        f"//   external matrix MDS                  = {checks['external_is_mds']}"
        + (
            ""
            if checks["external_is_mds"]
            else f"  <-- see note, minimal singular minor size "
            f"{checks['external_min_singular_minor'][0]} at rows "
            f"{checks['external_min_singular_minor'][1]}, cols "
            f"{checks['external_min_singular_minor'][2]}"
        ),
        f"//   internal matrix invertible           = {checks['internal_invertible']}",
        f"//   internal 1*1^T + diag(mu-1) form     = {checks['internal_form_ones_plus_diag']}",
        f"//   internal check_minpoly_condition     = {checks['internal_minpoly_condition']}",
        f"//   internal eprint 2020/500 algorithm 1 = {checks['internal_algorithm_1']}",
        f"//   internal eprint 2020/500 algorithm 2 = {checks['internal_algorithm_2']}",
        f"//   internal eprint 2020/500 algorithm 3 = {checks['internal_algorithm_3']}",
        f"//   Grain draws to accept the internal matrix = {checks['internal_grain_draws']}",
        "//",
        "// Note on the external matrix. circ(2*M4, M4, ..., M4) is NOT MDS for",
        "// t > 4, over any field, and that is by design, not a generation defect.",
        "// eprint 2023/323 Section 5, p.11: 'we show how to use non-MDS matrices",
        "// for the external and internal rounds, denoted respectively by M_E and",
        "// M_I ... this modification has no impact regarding the final security.'",
        "// The 'This matrix is MDS for all primes we consider' sentence in Section",
        "// 5.1 refers to the 4x4 block M4 only. What is claimed for M_E is a branch",
        "// number b = t/4 + 4 (Section 7.1, p.17, citing Griffin eprint 2022/403",
        "// Prop. 1), i.e. b = 7 at t = 12, versus 13 for an MDS matrix.",
        "// Verified here: M4 is MDS exhaustively; M_E is invertible (integer",
        "// determinant -2^26); M_E is not MDS, minimal singular minor size 2",
        "// (within a block row, column j is 2*M4[:,j] and column j+4 is M4[:,j],",
        "// so det[[10,5],[8,4]] = 0); and b <= 7 by the explicit witness",
        "// x = (-s, -s, 3s), s = e_0, which has wt(x) + wt(M_E x) = 3 + 4 = 7,",
        "// matching the claimed value from above. The lower bound b >= 7 is",
        "// imported from Griffin Prop. 1, not re-proved here.",
        "//",
        f"// Round numbers from the designers' security-driven search at M = 128:",
        f"//   R_F = {params['R_F']}, R_P = {params['R_P']}, "
        f"S-boxes = {checks['num_sboxes']}, "
        f"degree-{alpha} Plonkish constraints = {checks['plonkish_degree_alpha_constraints']}",
        "",
    ]

    body = [
        "",
        "use crate::declare_poseidon2_instance;",
        "",
        fmt_u64_array(
            "ROUND_CONSTANTS",
            params["round_constants"],
            "/// Grain-LFSR round constants, flat `(R_F + R_P) * t` layout.\n"
            "///\n"
            "/// Internal-round slots are `(c, 0, ..., 0)`, exactly as the\n"
            "/// Poseidon2 branch of `generate_constants` emits them.",
        ),
        "",
        fmt_u64_array(
            "INTERNAL_DIAG_M1",
            params["internal_diag_m1"],
            "/// Internal matrix diagonal minus one: `M_I = 1*1^T + diag(mu - 1)`.",
        ),
        "",
        "declare_poseidon2_instance!(",
        f"    Alpha{alpha},",
        f"    alpha = {alpha},",
        f"    rounds_f = {params['R_F']},",
        f"    rounds_p = {params['R_P']},",
        f'    tag = b"{tag}",',
        "    constants = ROUND_CONSTANTS,",
        "    diag = INTERNAL_DIAG_M1,",
        ");",
        "",
        "/// Full internal matrix, kept so tests can check the fast internal",
        "/// linear layer against the literal matrix the generator emitted.",
        "#[cfg(test)]",
        "#[rustfmt::skip]",
        f"pub(crate) const INTERNAL_MATRIX: [[u64; 12]; 12] = [",
    ]
    for row in params["internal_matrix"]:
        body.append("    [" + ", ".join(str(v) for v in row) + "],")
    body.append("];")
    body.append("")
    body.append("/// Full external matrix `circ(2*M4, M4, M4)`.")
    body.append("#[cfg(test)]")
    body.append("#[rustfmt::skip]")
    body.append("pub(crate) const EXTERNAL_MATRIX: [[u64; 12]; 12] = [")
    for row in params["external_matrix"]:
        body.append("    [" + ", ".join(str(v) for v in row) + "],")
    body.append("];")
    body.append("")
    body.append(
        "/// Known-answer vectors produced by the designers' own `poseidon2()`\n"
        "/// reference in the sage generator, re-derived independently by\n"
        "/// `tools/poseidon2_sponge_reference.py`."
    )
    body.append("#[cfg(test)]")
    body.append("#[rustfmt::skip]")
    body.append(
        f"pub(crate) const PERMUTATION_KATS: [([u64; 12], [u64; 12]); {len(params['kats'])}] = ["
    )
    for kat in params["kats"]:
        body.append(
            "    (["
            + ", ".join(str(v) for v in kat["input"])
            + "], ["
            + ", ".join(str(v) for v in kat["output"])
            + "]),"
        )
    body.append("];")
    body.append("")

    return head + "\n".join(verification) + "\n".join(body)


def emit_vectors(vectors, script_sha, sage_version):
    head = BANNER.format(
        alpha="<3|7>",
        script_sha=script_sha,
        date=datetime.date.today().isoformat(),
        sage_version=sage_version,
    )
    out = [
        head,
        "//",
        "// Sponge known-answer vectors from `tools/poseidon2_sponge_reference.py`,",
        "// an independent Python implementation of the permutation (naive matrix",
        "// form), the duplex, and the (A1)/(S1)/(S2) byte encodings.",
        "",
        "/// One step of a sponge known-answer script.",
        "pub(crate) enum SpongeOp {",
        "    Absorb(&'static [u8]),",
        "    SqueezeBytes(&'static [u8]),",
        "    SqueezeField(&'static [u64]),",
        "    Ratchet,",
        "}",
        "",
        "/// A named sponge known-answer script.",
        "pub(crate) struct SpongeKat {",
        "    pub name: &'static str,",
        "    pub ops: &'static [SpongeOp],",
        "}",
        "",
    ]
    for key in sorted(vectors):
        alpha = int(key.replace("alpha", ""))
        out.append("#[rustfmt::skip]")
        out.append(f"pub(crate) const SPONGE_KATS_ALPHA{alpha}: &[SpongeKat] = &[")
        for kat in vectors[key]["sponge_kats"]:
            out.append(f'    SpongeKat {{ name: "{kat["name"]}", ops: &[')
            for op in kat["ops"]:
                if op["op"] == "absorb":
                    payload = ", ".join(str(b) for b in op["bytes"])
                    out.append(f"        SpongeOp::Absorb(&[{payload}]),")
                elif op["op"] == "squeeze":
                    payload = ", ".join(str(b) for b in op["out"])
                    out.append(f"        SpongeOp::SqueezeBytes(&[{payload}]),")
                elif op["op"] == "squeeze_field":
                    payload = ", ".join(str(b) for b in op["out"])
                    out.append(f"        SpongeOp::SqueezeField(&[{payload}]),")
                elif op["op"] == "ratchet":
                    out.append("        SpongeOp::Ratchet,")
                else:
                    raise ValueError(op["op"])
            out.append("    ] },")
        out.append("];")
        out.append("")
    return "\n".join(out)


def main():
    a3_path, a7_path, vectors_path, out_dir = sys.argv[1:5]
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "poseidon2_params_p64m59.sage"), "rb") as fh:
        script_sha = hashlib.sha256(fh.read()).hexdigest()
    sage_version = os.environ.get("SAGE_VERSION", "SageMath (version recorded by the caller)")

    for path in (a3_path, a7_path):
        with open(path) as fh:
            params = json.load(fh)
        alpha = params["alpha"]
        target = os.path.join(out_dir, f"generated_alpha{alpha}.rs")
        with open(target, "w") as fh:
            fh.write(emit_params(params, script_sha, sage_version))
        print(f"wrote {target}", file=sys.stderr)

    with open(vectors_path) as fh:
        vectors = json.load(fh)
    target = os.path.join(out_dir, "generated_vectors.rs")
    with open(target, "w") as fh:
        fh.write(emit_vectors(vectors, script_sha, sage_version))
    print(f"wrote {target}", file=sys.stderr)


if __name__ == "__main__":
    main()
