# Poseidon2 parameter generator for p* = 2^64 - 59, t = 12.
#
# RESEARCH USE ONLY. The instance produced here is a NEW Poseidon2
# instantiation at a prime that nobody runs in production and for which no
# third-party cryptanalysis exists. Do not deploy.
#
# Provenance
# ----------
# This file is a parameterised fork of the designers' own script
#   https://github.com/HorizenLabs/poseidon2/blob/main/poseidon2_rust_params.sage
# vendored next to it as `upstream_poseidon2_rust_params.sage.txt`
#   sha256 c301c6d074b58cc27f117f59971f405a16c57d10e6140f1025643fa25ba75223
# (downloaded 2026-08-01 from raw.githubusercontent.com, branch main).
#
# Differences from upstream, all deliberate and listed exhaustively:
#   1. `p` and `t` are fixed to p* = 2^64 - 59 and t = 12 (upstream expects the
#      user to edit the top of the file).
#   2. `alpha` is taken from argv instead of being forced to the smallest
#      exponent coprime to p-1, so that both the alpha = 3 (smallest-coprime
#      convention) and alpha = 7 (published-Goldilocks round structure)
#      instances can be generated by the same code path.
#   3. `algorithm_1` calls `mat_test.eigenspaces_right(format='galois')` and
#      then immediately `continue`s on every eigenvalue that is not in F.
#      Constructing GF(p^k) for p ~ 2^64 and k up to 12 is prohibitively slow
#      and the result is discarded, so the F-rational eigenspaces are computed
#      directly from the roots of the characteristic polynomial in F. This is
#      the same set of subspaces the upstream code ends up using.
#   4. Output is JSON on stdout (upstream prints a Rust `lazy_static!` block
#      for the bellman_ce BLS12-381 scalar field) plus explicit verification
#      results.
#   5. Two known-answer vectors are emitted from the upstream `poseidon2()`
#      reference permutation so the Rust port can be cross-checked against the
#      designers' own implementation.
#
# Everything else - round-number search (`find_FD_round_numbers`,
# `sat_inequiv_alpha` including the eprint 2023/537 `cost_gb4` correction), the
# Grain LFSR, the constant-rejection rule, `generate_matrix_full`,
# `generate_matrix_partial`, `check_minpoly_condition`, `algorithm_2`,
# `algorithm_3`, and the `poseidon2()` reference permutation - is upstream code
# copied verbatim.
#
# Usage:
#   sage crates/akita-transcript/tools/poseidon2_params_p64m59.sage 3
#   sage crates/akita-transcript/tools/poseidon2_params_p64m59.sage 7

from math import *
import itertools
import json
import sys

p = 18446744073709551557  # 2^64 - 59
t = 12

_argv = [a for a in sys.argv[1:] if not a.endswith('.sage') and not a.endswith('.py')]
alpha = int(_argv[-1]) if _argv else 3
assert gcd(alpha, p - 1) == 1, "alpha must be coprime to p-1"

n = len(Integer(p).bits())  # 64

FIELD = 1
SBOX = 0
FIELD_SIZE = n
NUM_CELLS = t

# ---------------------------------------------------------------------------
# Round numbers (upstream, verbatim)
# ---------------------------------------------------------------------------

def get_sbox_cost(R_F, R_P, N, t):
    return int(t * R_F + R_P)

def get_size_cost(R_F, R_P, N, t):
    n = ceil(float(N) / t)
    return int((N * R_F) + (n * R_P))

def poseidon_calc_final_numbers_fixed(p, t, alpha, M, security_margin):
    n = ceil(log(p, 2))
    N = int(n * t)
    cost_function = get_sbox_cost
    ret_list = []
    (R_F, R_P) = find_FD_round_numbers(p, t, alpha, M, cost_function, security_margin)
    min_sbox_cost = cost_function(R_F, R_P, N, t)
    ret_list.append(R_F)
    ret_list.append(R_P)
    ret_list.append(min_sbox_cost)
    min_size_cost = get_size_cost(R_F, R_P, N, t)
    ret_list.append(min_size_cost)
    return ret_list

def find_FD_round_numbers(p, t, alpha, M, cost_function, security_margin):
    n = ceil(log(p, 2))
    N = int(n * t)
    sat_inequiv = sat_inequiv_alpha
    R_P = 0
    R_F = 0
    min_cost = float("inf")
    max_cost_rf = 0
    for R_P_t in range(1, 500):
        for R_F_t in range(4, 100):
            if R_F_t % 2 == 0:
                if (sat_inequiv(p, t, R_F_t, R_P_t, alpha, M) == True):
                    if security_margin == True:
                        R_F_t += 2
                        R_P_t = int(ceil(float(R_P_t) * 1.075))
                    cost = cost_function(R_F_t, R_P_t, N, t)
                    if (cost < min_cost) or ((cost == min_cost) and (R_F_t < max_cost_rf)):
                        R_P = ceil(R_P_t)
                        R_F = ceil(R_F_t)
                        min_cost = cost
                        max_cost_rf = R_F
    return (int(R_F), int(R_P))

def sat_inequiv_alpha(p, t, R_F, R_P, alpha, M):
    N = int(FIELD_SIZE * NUM_CELLS)

    if alpha > 0:
        R_F_1 = 6 if M <= ((floor(log(p, 2) - ((alpha-1)/2.0))) * (t + 1)) else 10 # Statistical
        R_F_2 = 1 + ceil(log(2, alpha) * min(M, FIELD_SIZE)) + ceil(log(t, alpha)) - R_P # Interpolation
        R_F_3 = (log(2, alpha) * min(M, log(p, 2))) - R_P # Groebner 1
        R_F_4 = t - 1 + log(2, alpha) * min(M / float(t + 1), log(p, 2) / float(2)) - R_P # Groebner 2
        R_F_5 = (t - 2 + (M / float(2 * log(alpha, 2))) - R_P) / float(t - 1) # Groebner 3
        R_F_max = max(ceil(R_F_1), ceil(R_F_2), ceil(R_F_3), ceil(R_F_4), ceil(R_F_5))

        # Addition due to https://eprint.iacr.org/2023/537.pdf
        r_temp = floor(t / 3.0)
        over = (R_F - 1) * t + R_P + r_temp + r_temp * (R_F / 2.0) + R_P + alpha
        under = r_temp * (R_F / 2.0) + R_P + alpha
        binom_log = log(binomial(over, under), 2)
        if binom_log == inf:
            binom_log = M + 1
        cost_gb4 = ceil(2 * binom_log) # Paper uses 2.3727, we are more conservative here

        return ((R_F >= R_F_max) and (cost_gb4 >= M))
    else:
        print("Invalid value for alpha!")
        exit(1)

R_F_FIXED, R_P_FIXED, SBOX_COST, SIZE_COST = poseidon_calc_final_numbers_fixed(p, t, alpha, 128, True)
sys.stderr.write("+++ alpha = {0}, R_F = {1}, R_P = {2}, sboxes = {3} +++\n".format(alpha, R_F_FIXED, R_P_FIXED, SBOX_COST))

# ---------------------------------------------------------------------------
# Grain LFSR and constants (upstream, verbatim)
# ---------------------------------------------------------------------------

INIT_SEQUENCE = []
PRIME_NUMBER = p
F = GF(PRIME_NUMBER)

def grain_sr_generator():
    bit_sequence = INIT_SEQUENCE
    for _ in range(0, 160):
        new_bit = bit_sequence[62] ^^ bit_sequence[51] ^^ bit_sequence[38] ^^ bit_sequence[23] ^^ bit_sequence[13] ^^ bit_sequence[0]
        bit_sequence.pop(0)
        bit_sequence.append(new_bit)

    while True:
        new_bit = bit_sequence[62] ^^ bit_sequence[51] ^^ bit_sequence[38] ^^ bit_sequence[23] ^^ bit_sequence[13] ^^ bit_sequence[0]
        bit_sequence.pop(0)
        bit_sequence.append(new_bit)
        while new_bit == 0:
            new_bit = bit_sequence[62] ^^ bit_sequence[51] ^^ bit_sequence[38] ^^ bit_sequence[23] ^^ bit_sequence[13] ^^ bit_sequence[0]
            bit_sequence.pop(0)
            bit_sequence.append(new_bit)
            new_bit = bit_sequence[62] ^^ bit_sequence[51] ^^ bit_sequence[38] ^^ bit_sequence[23] ^^ bit_sequence[13] ^^ bit_sequence[0]
            bit_sequence.pop(0)
            bit_sequence.append(new_bit)
        new_bit = bit_sequence[62] ^^ bit_sequence[51] ^^ bit_sequence[38] ^^ bit_sequence[23] ^^ bit_sequence[13] ^^ bit_sequence[0]
        bit_sequence.pop(0)
        bit_sequence.append(new_bit)
        yield new_bit

def grain_random_bits(num_bits):
    random_bits = [next(grain_gen) for i in range(0, num_bits)]
    random_int = int("".join(str(i) for i in random_bits), 2)
    return random_int

def init_generator(field, sbox, n, t, R_F, R_P):
    bit_list_field = [_ for _ in (bin(FIELD)[2:].zfill(2))]
    bit_list_sbox = [_ for _ in (bin(SBOX)[2:].zfill(4))]
    bit_list_n = [_ for _ in (bin(FIELD_SIZE)[2:].zfill(12))]
    bit_list_t = [_ for _ in (bin(NUM_CELLS)[2:].zfill(12))]
    bit_list_R_F = [_ for _ in (bin(R_F)[2:].zfill(10))]
    bit_list_R_P = [_ for _ in (bin(R_P)[2:].zfill(10))]
    bit_list_1 = [1] * 30
    global INIT_SEQUENCE
    INIT_SEQUENCE = bit_list_field + bit_list_sbox + bit_list_n + bit_list_t + bit_list_R_F + bit_list_R_P + bit_list_1
    INIT_SEQUENCE = [int(_) for _ in INIT_SEQUENCE]

def generate_constants(field, n, t, R_F, R_P, prime_number):
    round_constants = []
    num_constants = (R_F * t) + R_P # Poseidon2
    if field == 1:
        for i in range(0, num_constants):
            random_int = grain_random_bits(n)
            while random_int >= prime_number:
                random_int = grain_random_bits(n)
            round_constants.append(random_int)
            # Add (t-1) zeroes for Poseidon2 if partial round
            if i >= ((R_F/2) * t) and i < (((R_F/2) * t) + R_P):
                round_constants.extend([0] * (t-1))
    return round_constants

# ---------------------------------------------------------------------------
# Linear-layer checks (upstream; algorithm_1 eigenspace step re-expressed)
# ---------------------------------------------------------------------------

def generate_vectorspace(round_num, M, M_round, NUM_CELLS):
    t = NUM_CELLS
    s = 1
    V = VectorSpace(F, t)
    if round_num == 0:
        return V
    elif round_num == 1:
        return V.subspace(V.basis()[s:])
    else:
        mat_temp = matrix(F)
        for i in range(0, round_num-1):
            add_rows = []
            for j in range(0, s):
                add_rows.append(M_round[i].rows()[j][s:])
            mat_temp = matrix(mat_temp.rows() + add_rows)
        r_k = mat_temp.right_kernel()
        extended_basis_vectors = []
        for vec in r_k.basis():
            extended_basis_vectors.append(vector([0]*s + list(vec)))
        S = V.subspace(extended_basis_vectors)
        return S

def subspace_times_matrix(subspace, M, NUM_CELLS):
    t = NUM_CELLS
    V = VectorSpace(F, t)
    subspace_basis = subspace.basis()
    new_basis = []
    for vec in subspace_basis:
        new_basis.append(M * vec)
    new_subspace = V.subspace(new_basis)
    return new_subspace

def rational_eigenspaces(M, t):
    """F-rational right eigenspaces of M.

    Upstream calls `M.eigenspaces_right(format='galois')` and skips every
    eigenvalue outside F, so only the F-rational part is ever used. Building
    GF(p^k) for p ~ 2^64 is unnecessary and extremely slow, so the rational
    eigenvalues are obtained as the roots in F of the characteristic
    polynomial and the eigenspaces as the right kernels of (M - lambda*I).
    """
    V = VectorSpace(F, t)
    out = []
    for (root, _mult) in M.charpoly().roots():
        ker = (M - root * matrix.identity(F, t)).right_kernel()
        out.append(V.subspace(ker.basis()))
    return out

def algorithm_1(M, NUM_CELLS):
    t = NUM_CELLS
    s = 1
    r = floor((t - s) / float(s))

    M_round = []
    for j in range(0, t+1):
        M_round.append(M^(j+1))

    for i in range(1, r+1):
        mat_test = M^i
        entry = mat_test[0, 0]
        mat_target = matrix.circulant(vector([entry] + ([F(0)] * (t-1))))

        if (mat_test - mat_target) == matrix.circulant(vector([F(0)] * (t))):
            return [False, 1]

        S = generate_vectorspace(i, M, M_round, t)
        V = VectorSpace(F, t)

        basis_vectors = []
        for vector_subspace in rational_eigenspaces(mat_test, t):
            intersection = S.intersection(vector_subspace)
            basis_vectors += intersection.basis()
        IS = V.subspace(basis_vectors)

        if IS.dimension() >= 1 and IS != V:
            return [False, 2]
        for j in range(1, i+1):
            S_mat_mul = subspace_times_matrix(S, M^j, t)
            if S == S_mat_mul:
                return [False, 3]

    return [True, 0]

def algorithm_2(M, NUM_CELLS):
    t = NUM_CELLS
    s = 1

    V = VectorSpace(F, t)
    test_next = False
    I = range(0, s)
    I_powerset = list(sage.misc.misc.powerset(I))[1:]
    for I_s in I_powerset:
        test_next = False
        new_basis = []
        for l in I_s:
            new_basis.append(V.basis()[l])
        IS = V.subspace(new_basis)
        for i in range(s, t):
            new_basis.append(V.basis()[i])
        full_iota_space = V.subspace(new_basis)
        for l in I_s:
            v = V.basis()[l]
            while True:
                delta = IS.dimension()
                v = M * v
                IS = V.subspace(IS.basis() + [v])
                if IS.dimension() == t or IS.intersection(full_iota_space) != IS:
                    test_next = True
                    break
                if IS.dimension() <= delta:
                    break
            if test_next == True:
                break
        if test_next == True:
            continue
        return [False, [IS, I_s]]

    return [True, None]

def algorithm_3(M, NUM_CELLS):
    t = NUM_CELLS
    l = 4*t
    for r in range(2, l+1):
        res_alg_2 = algorithm_2(M^r, t)
        if res_alg_2[0] == False:
            return [False, None]
    return [True, None]

def check_minpoly_condition(M, NUM_CELLS):
    max_period = 2*NUM_CELLS
    all_fulfilled = True
    M_temp = M
    for i in range(1, max_period + 1):
        if not ((M_temp.minimal_polynomial().degree() == NUM_CELLS) and (M_temp.minimal_polynomial().is_irreducible() == True)):
            all_fulfilled = False
            break
        M_temp = M * M_temp
    return all_fulfilled

def generate_matrix_full(NUM_CELLS):
    M = None
    if t == 4:
        M = matrix(F, [[F(5), F(7), F(1), F(3)], [F(4), F(6), F(1), F(1)], [F(1), F(3), F(5), F(7)], [F(1), F(1), F(4), F(6)]])
    elif (t % 4) == 0:
        M = matrix(F, t, t)
        M_small = matrix(F, [[F(5), F(7), F(1), F(3)], [F(4), F(6), F(1), F(1)], [F(1), F(3), F(5), F(7)], [F(1), F(1), F(4), F(6)]])
        small_num = t // 4
        for i in range(0, small_num):
            for j in range(0, small_num):
                if i == j:
                    M[i*4:(i+1)*4,j*4:(j+1)*4] = 2 * M_small
                else:
                    M[i*4:(i+1)*4,j*4:(j+1)*4] = M_small
    else:
        raise ValueError("No external matrix for these parameters.")
    return M

def generate_matrix_partial(FIELD, FIELD_SIZE, NUM_CELLS):
    entry_max_bit_size = FIELD_SIZE
    M_circulant = matrix.circulant(vector([F(0)] + [F(1) for _ in range(0, NUM_CELLS - 1)]))
    M_diagonal = matrix.diagonal([F(grain_random_bits(entry_max_bit_size)) for _ in range(0, NUM_CELLS)])
    M = M_circulant + M_diagonal
    tries = 1
    while check_minpoly_condition(M, NUM_CELLS) == False:
        M_diagonal = matrix.diagonal([F(grain_random_bits(entry_max_bit_size)) for _ in range(0, NUM_CELLS)])
        M = M_circulant + M_diagonal
        tries += 1
    sys.stderr.write("internal matrix accepted after {0} Grain draw(s)\n".format(tries))
    if (algorithm_1(M, NUM_CELLS)[0] == False or algorithm_2(M, NUM_CELLS)[0] == False or algorithm_3(M, NUM_CELLS)[0] == False):
        raise ValueError("Generated partial matrix is not secure w.r.t. subspace trails.")
    return M, tries

def matrix_partial_m_1(matrix_partial, NUM_CELLS):
    M_circulant = matrix.identity(F, NUM_CELLS)
    return matrix_partial - M_circulant

# ---------------------------------------------------------------------------
# Reference permutation (upstream, verbatim) - used for the Rust cross-check
# ---------------------------------------------------------------------------

def poseidon2(input_words, matrix_full, matrix_partial, round_constants):
    R_f = int(R_F_FIXED / 2)
    round_constants_counter = 0
    state_words = list(input_words)

    # First matrix mul
    state_words = list(matrix_full * vector(state_words))

    # First full rounds
    for r in range(0, R_f):
        for i in range(0, t):
            state_words[i] = state_words[i] + round_constants[round_constants_counter]
            round_constants_counter += 1
        for i in range(0, t):
            state_words[i] = (state_words[i])^alpha
        state_words = list(matrix_full * vector(state_words))

    # Middle partial rounds
    for r in range(0, R_P_FIXED):
        for i in range(0, t):
            state_words[i] = state_words[i] + round_constants[round_constants_counter]
            round_constants_counter += 1
        state_words[0] = (state_words[0])^alpha
        state_words = list(matrix_partial * vector(state_words))

    # Last full rounds
    for r in range(0, R_f):
        for i in range(0, t):
            state_words[i] = state_words[i] + round_constants[round_constants_counter]
            round_constants_counter += 1
        for i in range(0, t):
            state_words[i] = (state_words[i])^alpha
        state_words = list(matrix_full * vector(state_words))

    return state_words

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------

grain_gen = grain_sr_generator()
init_generator(FIELD, SBOX, FIELD_SIZE, NUM_CELLS, R_F_FIXED, R_P_FIXED)

round_constants = generate_constants(FIELD, FIELD_SIZE, NUM_CELLS, R_F_FIXED, R_P_FIXED, PRIME_NUMBER)
assert len(round_constants) == (R_F_FIXED + R_P_FIXED) * t

MATRIX_FULL = generate_matrix_full(NUM_CELLS)
MATRIX_PARTIAL, INTERNAL_TRIES = generate_matrix_partial(FIELD, FIELD_SIZE, NUM_CELLS)
MATRIX_PARTIAL_DIAGONAL_M_1 = [matrix_partial_m_1(MATRIX_PARTIAL, NUM_CELLS)[i, i] for i in range(0, NUM_CELLS)]

# --- verification -----------------------------------------------------------

M4 = matrix(F, [[F(5), F(7), F(1), F(3)], [F(4), F(6), F(1), F(1)], [F(1), F(3), F(5), F(7)], [F(1), F(1), F(4), F(6)]])

def is_mds(M, size):
    """Exhaustive MDS test: every square submatrix is nonsingular."""
    rows = list(range(size))
    for k in range(1, size + 1):
        for rs in itertools.combinations(rows, k):
            for cs in itertools.combinations(rows, k):
                if M[list(rs), list(cs)].determinant() == 0:
                    return False
    return True

def min_singular_minor(M, size, max_k):
    """Smallest singular square submatrix, searching sizes 1..max_k.

    Returns (k, rows, cols) or None. Used to record how far the t > 4
    Poseidon2 external matrix is from MDS; see the note in the emitted header.
    """
    for k in range(1, max_k + 1):
        for rs in itertools.combinations(range(size), k):
            for cs in itertools.combinations(range(size), k):
                if M[list(rs), list(cs)].determinant() == 0:
                    return (int(k), [int(r) for r in rs], [int(c) for c in cs])
    return None

checks = {}
checks["m4_mds_exhaustive"] = bool(is_mds(M4, 4))
checks["external_invertible"] = bool(MATRIX_FULL.is_invertible())
# The t > 4 external matrix is NOT MDS: within any block row, column j and
# column j+4 are proportional (2*M4[:,j] versus M4[:,j]), so the 2x2 minor on
# rows {0,1} and columns {0,4} vanishes over every field. This is a property of
# the circ(2*M4, M4, ...) construction, not of this instance or this prime.
# Recorded rather than asserted; searching sizes 1..3 is enough to pin it down.
checks["external_min_singular_minor"] = min_singular_minor(MATRIX_FULL, t, 3)
checks["external_is_mds"] = checks["external_min_singular_minor"] is None
checks["external_charpoly_degree"] = int(MATRIX_FULL.charpoly().degree())
checks["internal_invertible"] = bool(MATRIX_PARTIAL.is_invertible())
checks["internal_minpoly_condition"] = bool(check_minpoly_condition(MATRIX_PARTIAL, NUM_CELLS))
checks["internal_algorithm_1"] = bool(algorithm_1(MATRIX_PARTIAL, NUM_CELLS)[0])
checks["internal_algorithm_2"] = bool(algorithm_2(MATRIX_PARTIAL, NUM_CELLS)[0])
checks["internal_algorithm_3"] = bool(algorithm_3(MATRIX_PARTIAL, NUM_CELLS)[0])
# M_I must be exactly 1*1^T + diag(mu - 1), i.e. off-diagonal 1 and diagonal
# MATRIX_PARTIAL_DIAGONAL_M_1[i] + 1. This is the form the Rust fast internal
# layer assumes: (M_I x)_i = sum_j x_j + (mu_i - 1) x_i.
checks["internal_form_ones_plus_diag"] = bool(
    MATRIX_PARTIAL
    == matrix(F, t, t, lambda i, j: F(1))
    + matrix.diagonal([MATRIX_PARTIAL_DIAGONAL_M_1[i] for i in range(t)])
)
checks["external_form_circ_2m4"] = bool(
    MATRIX_FULL
    == matrix(F, t, t, lambda i, j: F(2 * M4[i % 4][j % 4]) if (i // 4) == (j // 4) else F(M4[i % 4][j % 4]))
)
checks["gcd_alpha_p_minus_1"] = int(gcd(alpha, p - 1))
checks["internal_grain_draws"] = int(INTERNAL_TRIES)
checks["num_round_constants"] = int(len(round_constants))
checks["num_sboxes"] = int(t * R_F_FIXED + R_P_FIXED)
checks["plonkish_degree_alpha_constraints"] = int(t * R_F_FIXED + R_P_FIXED - t + 1)

# --- known-answer vectors ---------------------------------------------------

kats = []
for kat_in in [[i for i in range(t)], [0] * t, [p - 1 - i for i in range(t)]]:
    state_in = vector([F(x) for x in kat_in])
    state_out = poseidon2(state_in, MATRIX_FULL, MATRIX_PARTIAL, round_constants)
    kats.append({
        "input": [int(x) for x in kat_in],
        "output": [int(x) for x in state_out],
    })

out = {
    "prime": int(p),
    "prime_hex": "0x" + hex(p)[2:],
    "t": int(t),
    "alpha": int(alpha),
    "R_F": int(R_F_FIXED),
    "R_P": int(R_P_FIXED),
    "security_level_bits": int(128),
    "round_constants": [int(c) for c in round_constants],
    "internal_diag_m1": [int(x) for x in MATRIX_PARTIAL_DIAGONAL_M_1],
    "internal_matrix": [[int(MATRIX_PARTIAL[i, j]) for j in range(t)] for i in range(t)],
    "external_matrix": [[int(MATRIX_FULL[i, j]) for j in range(t)] for i in range(t)],
    "m4": [[int(M4[i, j]) for j in range(4)] for i in range(4)],
    "checks": checks,
    "kats": kats,
}

print(json.dumps(out, default=lambda o: int(o)))
