// GENERATED FILE - DO NOT EDIT BY HAND.
//
// UNAUDITED RESEARCH CRYPTOGRAPHY - NOT FOR PRODUCTION.
// This is a new Poseidon2 instance over p* = 2^64 - 59, a prime at which no
// arithmetization-oriented permutation has received third-party cryptanalysis
// at full parameters. Do not deploy.
//
// Generated by:
//   sage crates/akita-transcript/tools/poseidon2_params_p64m59.sage 7 \
//       > alpha7.json
//   python3 crates/akita-transcript/tools/poseidon2_sponge_reference.py \
//       alpha3.json alpha7.json > vectors.json
//   python3 crates/akita-transcript/tools/emit_rust_params.py \
//       alpha3.json alpha7.json vectors.json crates/akita-transcript/src/poseidon2
//
// Generator: crates/akita-transcript/tools/poseidon2_params_p64m59.sage
//   sha256 3dacc5bde2dd605a8bcabc9d57d929a86a5d1edd359ec2041347def9366e522a
// Upstream:  crates/akita-transcript/tools/upstream_poseidon2_rust_params.sage.txt
//   (HorizenLabs/poseidon2 poseidon2_rust_params.sage,
//    sha256 c301c6d074b58cc27f117f59971f405a16c57d10e6140f1025643fa25ba75223)
// Generated on 2026-08-01 with SageMath version 10.5.beta7, Release Date: 2024-10-12.
//
// Verification performed by the generator (all must be true):
//   gcd(alpha, p-1)                      = 1
//   M4 MDS (exhaustive, all 69 minors)   = True
//   external matrix invertible           = True
//   external matrix MDS                  = False  <-- see note, minimal singular minor size 2 at rows [0, 1], cols [0, 4]
//   internal matrix invertible           = True
//   internal 1*1^T + diag(mu-1) form     = True
//   internal check_minpoly_condition     = True
//   internal eprint 2020/500 algorithm 1 = True
//   internal eprint 2020/500 algorithm 2 = True
//   internal eprint 2020/500 algorithm 3 = True
//   Grain draws to accept the internal matrix = 2
//
// Note on the external matrix. circ(2*M4, M4, ..., M4) is NOT MDS for
// t > 4, over any field, and that is by design, not a generation defect.
// eprint 2023/323 Section 5, p.11: 'we show how to use non-MDS matrices
// for the external and internal rounds, denoted respectively by M_E and
// M_I ... this modification has no impact regarding the final security.'
// The 'This matrix is MDS for all primes we consider' sentence in Section
// 5.1 refers to the 4x4 block M4 only. What is claimed for M_E is a branch
// number b = t/4 + 4 (Section 7.1, p.17, citing Griffin eprint 2022/403
// Prop. 1), i.e. b = 7 at t = 12, versus 13 for an MDS matrix.
// Verified here: M4 is MDS exhaustively; M_E is invertible (integer
// determinant -2^26); M_E is not MDS, minimal singular minor size 2
// (within a block row, column j is 2*M4[:,j] and column j+4 is M4[:,j],
// so det[[10,5],[8,4]] = 0); and b <= 7 by the explicit witness
// x = (-s, -s, 3s), s = e_0, which has wt(x) + wt(M_E x) = 3 + 4 = 7,
// matching the claimed value from above. The lower bound b >= 7 is
// imported from Griffin Prop. 1, not re-proved here.
//
// Round numbers from the designers' security-driven search at M = 128:
//   R_F = 8, R_P = 22, S-boxes = 118, degree-7 Plonkish constraints = 107

use crate::declare_poseidon2_instance;

/// Grain-LFSR round constants, flat `(R_F + R_P) * t` layout.
///
/// Internal-round slots are `(c, 0, ..., 0)`, exactly as the
/// Poseidon2 branch of `generate_constants` emits them.
#[rustfmt::skip]
const ROUND_CONSTANTS: [u64; 360] = [
    1431286215153372998, 3509349009260703107, 2289575380984896342, 10625215922958251110,
    17137022507167291684, 17143426961497010024, 9589775313463224365, 7736066733515538648,
    2217569167061322248, 10394930802584583083, 4612393375016695705, 5332470884919453534,
    8724526834049581439, 17673787971454860688, 2519987773101056005, 7999687124137420323,
    18312454652563306701, 15136091233824155669, 1257110570403430003, 5665449074466664773,
    16178737609685266571, 52855143527893348, 8084454992943870230, 2597062441266647183,
    3342624911463171251, 6781356195391537436, 4697929572322733707, 4179687232228901671,
    17841073646522133059, 18340176721233187897, 13152929999122219197, 6306257051437840427,
    4974451914008050921, 11258703678970285201, 581736081259960204, 18323286026903235604,
    10250026231324330997, 13321947507807660157, 13020725208899496943, 11416990495425192684,
    7221795794796219413, 2607917872900632985, 2591896057192169329, 10485489452304998145,
    9480186048908910015, 2645141845409940474, 16242299839765162610, 12203738590896308135,
    5395176197344543510, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    17941136338888340715, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    7559392505546762987, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    549633128904721280, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    15658455328409267684, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    10078371877170729592, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    2349868247408080783, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    13105911261634181239, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    12868653202234053626, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    9471330315555975806, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    4580289636625406680, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    13222733136951421572, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    4555032575628627551, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    7619130111929922899, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    4547848507246491777, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    5662043532568004632, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    15723873049665279492, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    13585630674756818185, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    6990417929677264473, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    6373257983538884779, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    1005856792729125863, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    17850970025369572891, 0, 0, 0,
    0, 0, 0, 0,
    0, 0, 0, 0,
    14306783492963476045, 12653264875831356889, 10887434669785806501, 7221072982690633460,
    9953585853856674407, 13497620366078753434, 18140292631504202243, 17311934738088402529,
    6686302214424395771, 11193071888943695519, 10233795775801758543, 3362219552562939863,
    8595401306696186761, 7753411262943026561, 12415218859476220947, 12517451587026875834,
    3257008032900598499, 2187469039578904770, 657675168296710415, 8659969869470208989,
    12526098871288378639, 12525853395769009329, 15388161689979551704, 7880966905416338909,
    2911694411222711481, 6420652251792580406, 323544930728360053, 11718666476052241225,
    2449132068789045592, 17993014181992530560, 15161788952257357966, 3788504801066818367,
    1282111773460545571, 8849495164481705550, 8380852402060721190, 2161980224591127360,
    2440151485689245146, 17521895002090134367, 13821005335130766955, 17513705631114265826,
    17068447856797239529, 17964439003977043993, 5685000919538239429, 11615940660682589106,
    2522854885180605258, 12584118968072796115, 17841258728624635591, 10821564568873127316,
];

/// Internal matrix diagonal minus one: `M_I = 1*1^T + diag(mu - 1)`.
#[rustfmt::skip]
const INTERNAL_DIAG_M1: [u64; 12] = [
    8702942527907868189, 3447159893350309029, 16331987863400672411, 17004721198375099348,
    14568842036851006852, 14031093640500276072, 8047796853787800359, 18176470296573070530,
    1733280390763076135, 15280460251950617887, 5319165528697198956, 4130010739946422934,
];

declare_poseidon2_instance!(
    Alpha7,
    alpha = 7,
    rounds_f = 8,
    rounds_p = 22,
    tag = b"akita-pcs/transcript/v1/p2a7",
    constants = ROUND_CONSTANTS,
    diag = INTERNAL_DIAG_M1,
);

/// Full internal matrix, kept so tests can check the fast internal
/// linear layer against the literal matrix the generator emitted.
#[cfg(test)]
#[rustfmt::skip]
pub(crate) const INTERNAL_MATRIX: [[u64; 12]; 12] = [
    [8702942527907868190, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 3447159893350309030, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 16331987863400672412, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 17004721198375099349, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 14568842036851006853, 1, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 14031093640500276073, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 8047796853787800360, 1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 18176470296573070531, 1, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1733280390763076136, 1, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 15280460251950617888, 1, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5319165528697198957, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4130010739946422935],
];

/// Full external matrix `circ(2*M4, M4, M4)`.
#[cfg(test)]
#[rustfmt::skip]
pub(crate) const EXTERNAL_MATRIX: [[u64; 12]; 12] = [
    [10, 14, 2, 6, 5, 7, 1, 3, 5, 7, 1, 3],
    [8, 12, 2, 2, 4, 6, 1, 1, 4, 6, 1, 1],
    [2, 6, 10, 14, 1, 3, 5, 7, 1, 3, 5, 7],
    [2, 2, 8, 12, 1, 1, 4, 6, 1, 1, 4, 6],
    [5, 7, 1, 3, 10, 14, 2, 6, 5, 7, 1, 3],
    [4, 6, 1, 1, 8, 12, 2, 2, 4, 6, 1, 1],
    [1, 3, 5, 7, 2, 6, 10, 14, 1, 3, 5, 7],
    [1, 1, 4, 6, 2, 2, 8, 12, 1, 1, 4, 6],
    [5, 7, 1, 3, 5, 7, 1, 3, 10, 14, 2, 6],
    [4, 6, 1, 1, 4, 6, 1, 1, 8, 12, 2, 2],
    [1, 3, 5, 7, 1, 3, 5, 7, 2, 6, 10, 14],
    [1, 1, 4, 6, 1, 1, 4, 6, 2, 2, 8, 12],
];

/// Known-answer vectors produced by the designers' own `poseidon2()`
/// reference in the sage generator, re-derived independently by
/// `tools/poseidon2_sponge_reference.py`.
#[cfg(test)]
#[rustfmt::skip]
pub(crate) const PERMUTATION_KATS: [([u64; 12], [u64; 12]); 3] = [
    ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], [15885134513720636171, 1072628415468182552, 1295319757680701546, 12832175991882310548, 4904985868749470305, 5110221144556265988, 17090233063206682078, 13870953051952550766, 16338497826224187287, 634098903830233761, 17029844430997970992, 16614035742128067589]),
    ([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [15116890061224744310, 440432794729914275, 8384676134460908670, 17259600748529071728, 16224704619638215441, 11536474258570263387, 11991502552278032984, 3684835073418390338, 2807673596805381011, 7425353901840308863, 17397898347780197840, 10551928813583876409]),
    ([18446744073709551556, 18446744073709551555, 18446744073709551554, 18446744073709551553, 18446744073709551552, 18446744073709551551, 18446744073709551550, 18446744073709551549, 18446744073709551548, 18446744073709551547, 18446744073709551546, 18446744073709551545], [12929809194768593548, 9789398672086031117, 758278514497712333, 18001985184557988103, 5305507473918894690, 3435719949254227029, 9855110349342941214, 4668132878222456257, 9423636030781853313, 8751212570579399202, 12274235031767831045, 11417320091504233982]),
];
